spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/currencyconverter
    username: ccappuser
    password: ccapp@123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

freecurrencyapi:
  api-key: fca_live_QIJakmPhJXBdGVWZYJlsMU1nSZlN7c02jOoMEbe4
  base-url: https://api.freecurrencyapi.com/v1
