server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/currencyconverter
    username: ccappuser
    password: ccapp@123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

freecurrencyapi:
  api-key: fca_live_QIJakmPhJXBdGVWZYJlsMU1nSZlN7c02jOoMEbe4
  base-url: https://api.freecurrencyapi.com/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.example.currencyconverter: INFO
    org.springframework.web: INFO
